'use client'

import React, { useState } from 'react'
import { ShoppingCart, Stethoscope, Bell, Share2, Calendar, Download, X, Check, Loader2 } from 'lucide-react'
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'

interface ReminderData {
  medicineName: string
  time: string
  frequency: string
  notes: string
}

export function ActionButtons() {
  const [showReminderModal, setShowReminderModal] = useState(false)
  const [showShareModal, setShowShareModal] = useState(false)
  const [showConsultModal, setShowConsultModal] = useState(false)
  const [showOrderModal, setShowOrderModal] = useState(false)
  const [reminderData, setReminderData] = useState<ReminderData>({
    medicineName: '',
    time: '09:00',
    frequency: 'daily',
    notes: ''
  })
  const [isLoading, setIsLoading] = useState(false)
  const [success, setSuccess] = useState<string | null>(null)

  const handleGoogleCalendar = () => {
    const event = {
      text: `Take ${reminderData.medicineName || 'Medication'}`,
      details: reminderData.notes || 'Time to take your medication',
      dates: generateCalendarDates(reminderData.time),
    }
    
    const url = `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${encodeURIComponent(event.text)}&details=${encodeURIComponent(event.details)}&dates=${event.dates}`
    window.open(url, '_blank')
    setSuccess('Opening Google Calendar...')
    setTimeout(() => {
      setSuccess(null)
      setShowReminderModal(false)
    }, 1500)
  }

  const handleOutlookCalendar = () => {
    const event = {
      subject: `Take ${reminderData.medicineName || 'Medication'}`,
      body: reminderData.notes || 'Time to take your medication',
      startdt: generateOutlookDate(reminderData.time),
    }
    
    const url = `https://outlook.live.com/calendar/0/deeplink/compose?subject=${encodeURIComponent(event.subject)}&body=${encodeURIComponent(event.body)}&startdt=${event.startdt}`
    window.open(url, '_blank')
    setSuccess('Opening Microsoft Calendar...')
    setTimeout(() => {
      setSuccess(null)
      setShowReminderModal(false)
    }, 1500)
  }

  const handlePushNotification = async () => {
    if ('Notification' in window) {
      const permission = await Notification.requestPermission()
      if (permission === 'granted') {
        // Schedule notification (simplified - in production you'd use service workers)
        setSuccess('Push notifications enabled!')
        setTimeout(() => setSuccess(null), 2000)
      } else {
        setSuccess('Please enable notifications in browser settings')
        setTimeout(() => setSuccess(null), 3000)
      }
    }
  }

  const handleSharePDF = async () => {
    setIsLoading(true)
    try {
      // Generate PDF using browser's print functionality
      const printContent = `
        <html>
          <head>
            <title>Lumi Health Report</title>
            <style>
              body { font-family: Inter, system-ui, sans-serif; padding: 40px; color: #1a1a1a; }
              h1 { color: #3b82f6; margin-bottom: 8px; }
              .subtitle { color: #6b7280; font-size: 14px; margin-bottom: 32px; }
              .section { margin-bottom: 24px; padding: 16px; background: #f8fafc; border-radius: 8px; }
              .section-title { font-weight: 600; margin-bottom: 8px; }
              .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e5e7eb; font-size: 12px; color: #9ca3af; }
            </style>
          </head>
          <body>
            <h1>Lumi Health Report</h1>
            <p class="subtitle">Generated on ${new Date().toLocaleDateString()}</p>
            <div class="section">
              <p class="section-title">Prescription Analysis</p>
              <p>Your prescription has been analyzed by Lumi AI. Please consult with your healthcare provider for medical advice.</p>
            </div>
            <div class="section">
              <p class="section-title">Medications</p>
              <p>Review your medications and follow the prescribed schedule.</p>
            </div>
            <div class="footer">
              <p>Generated by Lumi - AI Digital Pharmacist</p>
              <p>This report is for informational purposes only and does not constitute medical advice.</p>
            </div>
          </body>
        </html>
      `
      
      const printWindow = window.open('', '_blank')
      if (printWindow) {
        printWindow.document.write(printContent)
        printWindow.document.close()
        printWindow.print()
      }
      
      setSuccess('PDF ready to download!')
    } catch (error) {
      console.error('[v0] PDF generation error:', error)
    } finally {
      setIsLoading(false)
      setTimeout(() => {
        setSuccess(null)
        setShowShareModal(false)
      }, 1500)
    }
  }

  const handleEmailShare = () => {
    const subject = encodeURIComponent('My Lumi Health Report')
    const body = encodeURIComponent('I wanted to share my health report from Lumi AI Digital Pharmacist.\n\nPlease review my prescription analysis.')
    window.location.href = `mailto:?subject=${subject}&body=${body}`
    setShowShareModal(false)
  }

  return (
    <>
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
        {/* Order Medicine */}
        <button 
          onClick={() => setShowOrderModal(true)}
          className="group glass-card hover:glass-card-elevated border border-blue-100 hover:border-blue-200 rounded-xl p-5 flex flex-col items-center justify-center gap-3 transition-all duration-300"
        >
          <div className="w-12 h-12 bg-gradient-to-br from-blue-500 to-indigo-500 rounded-xl flex items-center justify-center shadow-lg shadow-blue-500/20 group-hover:scale-105 transition-transform">
            <ShoppingCart className="w-6 h-6 text-white" />
          </div>
          <div className="text-center">
            <p className="font-semibold text-sm text-foreground">Order Medicine</p>
            <p className="text-xs text-muted-foreground">Get delivered</p>
          </div>
        </button>

        {/* Consult Doctor */}
        <button 
          onClick={() => setShowConsultModal(true)}
          className="group glass-card hover:glass-card-elevated border border-emerald-100 hover:border-emerald-200 rounded-xl p-5 flex flex-col items-center justify-center gap-3 transition-all duration-300"
        >
          <div className="w-12 h-12 bg-gradient-to-br from-emerald-500 to-teal-500 rounded-xl flex items-center justify-center shadow-lg shadow-emerald-500/20 group-hover:scale-105 transition-transform">
            <Stethoscope className="w-6 h-6 text-white" />
          </div>
          <div className="text-center">
            <p className="font-semibold text-sm text-foreground">Consult Doctor</p>
            <p className="text-xs text-muted-foreground">Talk online</p>
          </div>
        </button>

        {/* Set Reminder */}
        <button 
          onClick={() => setShowReminderModal(true)}
          className="group glass-card hover:glass-card-elevated border border-amber-100 hover:border-amber-200 rounded-xl p-5 flex flex-col items-center justify-center gap-3 transition-all duration-300"
        >
          <div className="w-12 h-12 bg-gradient-to-br from-amber-500 to-orange-500 rounded-xl flex items-center justify-center shadow-lg shadow-amber-500/20 group-hover:scale-105 transition-transform">
            <Bell className="w-6 h-6 text-white" />
          </div>
          <div className="text-center">
            <p className="font-semibold text-sm text-foreground">Set Reminder</p>
            <p className="text-xs text-muted-foreground">Never miss</p>
          </div>
        </button>

        {/* Share Report */}
        <button 
          onClick={() => setShowShareModal(true)}
          className="group glass-card hover:glass-card-elevated border border-violet-100 hover:border-violet-200 rounded-xl p-5 flex flex-col items-center justify-center gap-3 transition-all duration-300"
        >
          <div className="w-12 h-12 bg-gradient-to-br from-violet-500 to-purple-500 rounded-xl flex items-center justify-center shadow-lg shadow-violet-500/20 group-hover:scale-105 transition-transform">
            <Share2 className="w-6 h-6 text-white" />
          </div>
          <div className="text-center">
            <p className="font-semibold text-sm text-foreground">Share Report</p>
            <p className="text-xs text-muted-foreground">PDF export</p>
          </div>
        </button>
      </div>

      {/* Reminder Modal */}
      <Dialog open={showReminderModal} onOpenChange={setShowReminderModal}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Bell className="w-5 h-5 text-amber-500" />
              Set Medication Reminder
            </DialogTitle>
          </DialogHeader>
          
          {success ? (
            <div className="py-8 text-center">
              <div className="w-16 h-16 bg-emerald-100 rounded-full flex items-center justify-center mx-auto mb-4">
                <Check className="w-8 h-8 text-emerald-600" />
              </div>
              <p className="text-foreground font-medium">{success}</p>
            </div>
          ) : (
            <div className="space-y-4">
              <div>
                <label className="text-sm font-medium text-foreground">Medicine Name</label>
                <input
                  type="text"
                  value={reminderData.medicineName}
                  onChange={(e) => setReminderData({ ...reminderData, medicineName: e.target.value })}
                  placeholder="e.g., Metformin"
                  className="w-full mt-1 px-3 py-2 border border-border rounded-lg focus:outline-none focus:ring-2 focus:ring-primary/20"
                />
              </div>
              <div>
                <label className="text-sm font-medium text-foreground">Time</label>
                <input
                  type="time"
                  value={reminderData.time}
                  onChange={(e) => setReminderData({ ...reminderData, time: e.target.value })}
                  className="w-full mt-1 px-3 py-2 border border-border rounded-lg focus:outline-none focus:ring-2 focus:ring-primary/20"
                />
              </div>
              <div>
                <label className="text-sm font-medium text-foreground">Notes (optional)</label>
                <textarea
                  value={reminderData.notes}
                  onChange={(e) => setReminderData({ ...reminderData, notes: e.target.value })}
                  placeholder="Take with food..."
                  rows={2}
                  className="w-full mt-1 px-3 py-2 border border-border rounded-lg focus:outline-none focus:ring-2 focus:ring-primary/20 resize-none"
                />
              </div>
              
              <div className="pt-2 space-y-2">
                <p className="text-sm text-muted-foreground mb-2">Add to calendar:</p>
                <div className="grid grid-cols-2 gap-2">
                  <Button onClick={handleGoogleCalendar} variant="outline" className="w-full">
                    <Calendar className="w-4 h-4 mr-2 text-red-500" />
                    Google
                  </Button>
                  <Button onClick={handleOutlookCalendar} variant="outline" className="w-full">
                    <Calendar className="w-4 h-4 mr-2 text-blue-500" />
                    Microsoft
                  </Button>
                </div>
                <Button onClick={handlePushNotification} variant="outline" className="w-full">
                  <Bell className="w-4 h-4 mr-2" />
                  Enable Push Notifications
                </Button>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>

      {/* Share Modal */}
      <Dialog open={showShareModal} onOpenChange={setShowShareModal}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Share2 className="w-5 h-5 text-violet-500" />
              Share Report
            </DialogTitle>
          </DialogHeader>
          
          {success ? (
            <div className="py-8 text-center">
              <div className="w-16 h-16 bg-emerald-100 rounded-full flex items-center justify-center mx-auto mb-4">
                <Check className="w-8 h-8 text-emerald-600" />
              </div>
              <p className="text-foreground font-medium">{success}</p>
            </div>
          ) : (
            <div className="space-y-3">
              <Button onClick={handleSharePDF} className="w-full" disabled={isLoading}>
                {isLoading ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Download className="w-4 h-4 mr-2" />}
                Download as PDF
              </Button>
              <Button onClick={handleEmailShare} variant="outline" className="w-full">
                <Share2 className="w-4 h-4 mr-2" />
                Share via Email
              </Button>
            </div>
          )}
        </DialogContent>
      </Dialog>

      {/* Consult Doctor Modal */}
      <Dialog open={showConsultModal} onOpenChange={setShowConsultModal}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Stethoscope className="w-5 h-5 text-emerald-500" />
              Consult a Doctor
            </DialogTitle>
          </DialogHeader>
          
          <div className="py-4">
            <div className="bg-emerald-50 border border-emerald-100 rounded-xl p-4 mb-4">
              <p className="text-sm text-emerald-800">
                Connect with licensed healthcare professionals for medical advice about your prescription.
              </p>
            </div>
            
            <div className="space-y-3">
              <Button 
                onClick={() => window.open('https://www.healthgrades.com/', '_blank')}
                className="w-full bg-emerald-600 hover:bg-emerald-700"
              >
                Find Doctors Near You
              </Button>
              <Button 
                onClick={() => window.open('https://www.teladoc.com/', '_blank')}
                variant="outline" 
                className="w-full"
              >
                Telemedicine Consultation
              </Button>
            </div>
            
            <p className="text-xs text-muted-foreground mt-4 text-center">
              Lumi provides information only. Always consult a healthcare professional for medical advice.
            </p>
          </div>
        </DialogContent>
      </Dialog>

      {/* Order Medicine Modal */}
      <Dialog open={showOrderModal} onOpenChange={setShowOrderModal}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <ShoppingCart className="w-5 h-5 text-blue-500" />
              Order Medicine
            </DialogTitle>
          </DialogHeader>
          
          <div className="py-4">
            <div className="bg-blue-50 border border-blue-100 rounded-xl p-4 mb-4">
              <p className="text-sm text-blue-800">
                Order your prescribed medications from trusted pharmacies with home delivery.
              </p>
            </div>
            
            <div className="space-y-3">
              <Button 
                onClick={() => window.open('https://www.cvs.com/', '_blank')}
                className="w-full"
              >
                CVS Pharmacy
              </Button>
              <Button 
                onClick={() => window.open('https://www.walgreens.com/', '_blank')}
                variant="outline" 
                className="w-full"
              >
                Walgreens
              </Button>
              <Button 
                onClick={() => window.open('https://www.amazon.com/pharmacy', '_blank')}
                variant="outline" 
                className="w-full"
              >
                Amazon Pharmacy
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </>
  )
}

// Helper functions
function generateCalendarDates(time: string): string {
  const now = new Date()
  const [hours, minutes] = time.split(':')
  now.setHours(parseInt(hours), parseInt(minutes), 0)
  
  const start = now.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z'
  now.setMinutes(now.getMinutes() + 30)
  const end = now.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z'
  
  return `${start}/${end}`
}

function generateOutlookDate(time: string): string {
  const now = new Date()
  const [hours, minutes] = time.split(':')
  now.setHours(parseInt(hours), parseInt(minutes), 0)
  return now.toISOString()
}
